defaults_pg: &defaults_pg
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5

test:
  <<: *defaults_pg
  database: react_accounts_test

development:
  <<: *defaults_pg
  database: react_accounts_dev
